#!/usr/bin/env python3
"""End-to-end msa-ad example on synthetic data.

Runs both analyses and prints both reports:

1. Bench characterisation - Gage R&R on a continuous safety-margin metric
   (minimum time-to-collision), then the two-tier fixed-seed / varied-seed
   study that separates apparatus error from injected scenario stochasticity,
   then attribute agreement on the binary pass/fail verdicts.
2. Coverage-claim verification - seeded known faults through the campaign,
   then a claimed-versus-validated comparison.

The data is synthetic and is regenerated deterministically from a fixed seed.
Run with ``--regenerate`` to rewrite the committed CSVs.

    python example/run_example.py
    python example/run_example.py --regenerate
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from msa_ad import (  # noqa: E402
    BinaryDataError,
    MissingTierError,
    analyse_seeded_faults,
    attribute_agreement,
    compare_claimed_coverage,
    gage_rr_anova,
    render_attribute_report,
    render_coverage_claim_report,
    render_gage_rr_report,
    render_seeded_fault_report,
    render_two_tier_report,
    two_tier_gage_rr,
)
from msa_ad.datagen import (  # noqa: E402
    DEFAULT_SEED,
    DETERMINISTIC_BENCHES,
    TTC_PASS_THRESHOLD_S,
    generate_all,
)
from msa_ad.two_tier import TIER_VARIED_SEED  # noqa: E402

HERE = Path(__file__).resolve().parent
BENCH_RUNS = HERE / "bench_runs.csv"
BENCH_RUNS_TWO_TIER = HERE / "bench_runs_two_tier.csv"
FAULT_CATALOGUE = HERE / "fault_catalogue.csv"
CAMPAIGN_RESULTS = HERE / "campaign_results.csv"

#: Detection-rate floor the validation argument wants to defend.
DETECTION_THRESHOLD = 0.80

#: Coverage figure asserted elsewhere in the (fictional) safety case.
CLAIMED_COVERAGE = 0.95


def regenerate() -> None:
    tables = generate_all(DEFAULT_SEED)
    tables["bench_runs"].to_csv(BENCH_RUNS, index=False)
    tables["bench_runs_two_tier"].to_csv(BENCH_RUNS_TWO_TIER, index=False)
    tables["fault_catalogue"].to_csv(FAULT_CATALOGUE, index=False)
    tables["campaign_results"].to_csv(CAMPAIGN_RESULTS, index=False)
    print(f"wrote {BENCH_RUNS}")
    print(f"wrote {BENCH_RUNS_TWO_TIER}")
    print(f"wrote {FAULT_CATALOGUE}")
    print(f"wrote {CAMPAIGN_RESULTS}")


def banner(text: str) -> None:
    print()
    print("#" * 78)
    print(f"# {text}")
    print("#" * 78)
    print()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help="rewrite the committed synthetic CSVs and exit",
    )
    args = parser.parse_args()
    if args.regenerate:
        regenerate()
        return 0

    if not BENCH_RUNS.exists() or not BENCH_RUNS_TWO_TIER.exists():
        regenerate()

    runs = pd.read_csv(BENCH_RUNS)
    two_tier_runs = pd.read_csv(BENCH_RUNS_TWO_TIER)
    catalogue = pd.read_csv(FAULT_CATALOGUE)
    results = pd.read_csv(CAMPAIGN_RESULTS)

    print("=" * 78)
    print("msa-ad worked example")
    print("=" * 78)
    print(
        "ALL DATA BELOW IS SYNTHETIC. It was generated by msa_ad.datagen from\n"
        f"a fixed seed ({DEFAULT_SEED}) and is not measured data from any bench,\n"
        "programme or vehicle. It exists so the example is reproducible and so\n"
        "the tooling can be seen finding something."
    )
    print()
    print(f"bench runs        : {len(runs)} rows")
    print(f"two-tier runs     : {len(two_tier_runs)} rows")
    print(f"fault catalogue   : {len(catalogue)} rows")
    print(f"campaign results  : {len(results)} rows")
    print(
        f"pass criterion    : min_ttc_s >= {TTC_PASS_THRESHOLD_S:.2f} s"
    )

    # ---------------------------------------------------------------- 1a
    banner("1a. BENCH CHARACTERISATION - continuous metric (minimum TTC)")
    grr = gage_rr_anova(
        runs,
        scenario_col="scenario_id",
        bench_col="bench_id",
        value_col="min_ttc_s",
    )
    print(render_gage_rr_report(grr))

    # ---------------------------------------------------------------- 1b
    banner("1b. GUARD - binary verdicts must not go down the ANOVA path")
    try:
        gage_rr_anova(
            runs,
            scenario_col="scenario_id",
            bench_col="bench_id",
            value_col="verdict",
        )
    except BinaryDataError as exc:
        print("BinaryDataError raised, as it should be:")
        print()
        for line in str(exc).splitlines():
            print(f"    {line}" if line else "")
    else:  # pragma: no cover - would be a bug
        print("ERROR: no exception raised; the guard is broken")
        return 1

    # ---------------------------------------------------------------- 1c
    banner("1c. TWO-TIER STUDY - apparatus error vs injected scenario noise")
    declared = " and ".join(DETERMINISTIC_BENCHES)
    print(
        "The replicates in 1a were produced by varying the random seed, so\n"
        "their scatter is the apparatus *plus* the traffic-agent and\n"
        "sensor-noise models responding to that seed. The two-tier data set\n"
        "re-executes every scenario twice over: once with the seed held fixed,\n"
        "and once with it varied.\n"
        "\n"
        f"{declared} are documented as reproducing a fixed seed exactly.\n"
        "The audit below is what checks that, rather than assuming it.\n"
    )
    two_tier = two_tier_gage_rr(
        two_tier_runs,
        scenario_col="scenario_id",
        bench_col="bench_id",
        value_col="min_ttc_s",
        deterministic_benches=DETERMINISTIC_BENCHES,
    )
    print(render_two_tier_report(two_tier))

    # ---------------------------------------------------------------- 1d
    banner("1d. GUARD - a two-tier study needs both tiers")
    try:
        two_tier_gage_rr(
            two_tier_runs[two_tier_runs["tier"] == TIER_VARIED_SEED],
            value_col="min_ttc_s",
        )
    except MissingTierError as exc:
        print("MissingTierError raised, as it should be:")
        print()
        for line in str(exc).splitlines():
            print(f"    {line}" if line else "")
    else:  # pragma: no cover - would be a bug
        print("ERROR: no exception raised; the guard is broken")
        return 1

    # ---------------------------------------------------------------- 1e
    banner("1e. BENCH CHARACTERISATION - binary pass/fail verdicts")
    attr = attribute_agreement(
        runs,
        scenario_col="scenario_id",
        bench_col="bench_id",
        verdict_col="verdict",
    )
    print(render_attribute_report(attr))

    # ----------------------------------------------------------------- 2a
    banner("2a. COVERAGE-CLAIM VERIFICATION - seeded known faults")
    seeded = analyse_seeded_faults(
        catalogue, results, threshold=DETECTION_THRESHOLD
    )
    print(render_seeded_fault_report(seeded))

    # ----------------------------------------------------------------- 2b
    banner("2b. CLAIMED VERSUS VALIDATED COVERAGE")
    claim = compare_claimed_coverage(
        seeded,
        CLAIMED_COVERAGE,
        claim_label=(
            f"{CLAIMED_COVERAGE:.0%} of identified hazards covered by the "
            "Q2 campaign"
        ),
    )
    print(render_coverage_claim_report(claim))

    # -------------------------------------------------------------- summary
    banner("SUMMARY OF FINDINGS")
    worst = grr.per_bench_repeatability.sort_values(
        "repeatability_sd", ascending=False
    ).iloc[0]
    print(
        f"* Gage R&R on min_ttc_s: %GRR = {grr.pct_grr:.1f}% "
        f"({grr.verdict}), ndc = {grr.ndc} "
        f"(AIAG minimum 5: {'met' if grr.ndc_ok else 'NOT met'})."
    )
    print(
        f"* Bench {worst['bench']} dominates the repeatability term: "
        f"SD = {worst['repeatability_sd']:.3f} s, "
        f"{worst['sd_ratio_vs_best']:.1f}x the best bench."
    )
    print(
        f"* Two-tier split: the apparatus accounts for "
        f"{100.0 - two_tier.pct_aleatory_of_varied:.1f}% of the varied-seed "
        f"replicate variance;\n"
        f"  the other {two_tier.pct_aleatory_of_varied:.1f}% is injected "
        f"scenario stochasticity (SD {two_tier.aleatory_sd:.3f} s). A "
        f"single-tier study\n"
        f"  charges all of it to repeatability: %GRR "
        f"{two_tier.fixed_seed.pct_grr:.1f}% (Tier A) vs "
        f"{two_tier.varied_seed.pct_grr:.1f}% (Tier B)."
    )
    if two_tier.any_determinism_violation:
        offenders = two_tier.determinism_violations["bench"].tolist()
        print(
            f"* Determinism audit FAILED for {offenders}: declared to "
            "reproduce a fixed seed\n"
            "  exactly, and did not."
        )
    print(
        f"* Attribute agreement: between-bench strict reproducibility = "
        f"{attr.between_bench_strict[2]:.3f}, "
        f"Fleiss' kappa = {attr.fleiss_kappa_all_trials:.3f}."
    )
    print(
        f"* Coverage-validity ratio: {seeded.n_detected}/{seeded.n_expected} "
        f"= {seeded.detection_rate:.3f} "
        f"[{seeded.detection_ci[0]:.3f}, {seeded.detection_ci[1]:.3f}]."
    )
    flagged = seeded.flagged_classes["hazard_class"].tolist()
    print(
        f"* Hazard classes flagged at threshold {DETECTION_THRESHOLD:.2f}: "
        f"{flagged if flagged else 'none'}."
    )
    print(
        f"* Claimed coverage {CLAIMED_COVERAGE:.2f} vs measured "
        f"{claim.measured_rate:.3f}: discrepancy {claim.discrepancy:+.3f}, "
        f"claim {'inside' if claim.claim_within_ci else 'outside'} the "
        "95% interval."
    )
    print(
        f"* {len(seeded.not_executed)} catalogued fault(s) were never executed "
        "and are excluded from the ratio."
    )
    print()
    print(
        "Reminder: these findings are properties of synthetic data constructed\n"
        "to contain them. They demonstrate the tooling, not any real bench."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
